# SITE CONFIGURATION
baseurl: "/thecodeway" # set it to "/" if use for personal site. The subpath of your site, e.g. /blog/
baseurl: "/thecodeway" # the subpath of your site, e.g. /blog/
url: "http://hungking.cc/thecodeway" # the base hostname & protocol for your site
imageurl: "https://source.unsplash.com/category/nature/2600x500" #"https://unsplash.it/2600/500?random"

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: HOUNGKING HSI
  #avatar: avatar.png
  hometitle: Home #display on navigation menu.
  yoursitetitle: HOUNGKING HSI
  gravatar: # Email MD5 hash
  description: "this is my description." # used by search engines
  visiblewords: 500
  # Header and footer text
  header_text: >
     Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

  header_text_feature_image: img/sample_feature_img.png
  place_holder_image: img/sample_feature_img.png
  footer_text: >
   <a href="http://hungking.cc">HOUNGKING HSI</a> 

  # Icons
  rss: false
  email_address: "imisslovelove@live.com" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "houngkinghsi"
  weibo: 
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest: 
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "imisslovelove"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-57438264-1" # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: "imisslovelove"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  #str_next: "Next"
  #str_prev: "Prev"
  str_continue_reading: "Continue Reading..."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"
  
  # Post navigation
  post_navigation: false

# PAGINATION
enforce_ssl: "indeex.org"
paginate: 5
paginate_path: "blog/page:num"
permalink: blog/:title/  #Delete preurl 'thecodeway/' if used for your personal site.

# Posted in ... with ...
sechby: 
  category:   #in
  tag:   #with

# BUILD SETTINGS
markdown: redcarpet
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
